import { Document, Page, View, Text } from '@react-pdf/renderer';
import { styles, colors } from './pdf-styles';
import { PdfHeader } from './pdf-header';
import { PdfSciGauge } from './pdf-sci-gauge';
import { PdfCompareTable } from './pdf-compare-table';
import { PdfJourneyList } from './pdf-journey-list';
import { PdfPaymentTable } from './pdf-payment-table';
import { PdfContractorInfo } from './pdf-contractor-info';
import { PdfTerms } from './pdf-terms';
import type { Proposal, SequenceStep } from '@renonext/shared/types';
import type { ContractorProfileResponse, ProProfileResponse } from '@/lib/supabase/types';
import type { SCIResult } from '@/lib/utils/scope-confidence';
import type { PaymentMilestone } from '@/lib/utils/payment-milestones';

export interface ProposalPdfProps {
  proposal: Proposal;
  contractorProfile: ContractorProfileResponse;
  proProfile: ProProfileResponse | null;
  sci: SCIResult;
  milestones: PaymentMilestone[];
  steps: SequenceStep[];
}

export function ProposalPdfDocument({
  proposal,
  contractorProfile,
  proProfile,
  sci,
  milestones,
  steps,
}: ProposalPdfProps) {
  const companyName = proProfile?.company_name ?? contractorProfile.full_name;

  return (
    <Document
      title={proposal.title}
      author={contractorProfile.full_name}
      subject="Project Proposal"
      creator="RenoNext"
    >
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <PdfHeader
          title={proposal.title}
          contractorName={contractorProfile.full_name}
          companyName={companyName}
          sentAt={proposal.sent_at ?? proposal.created_at}
          expiresAt={proposal.expires_at}
          coverLetter={proposal.cover_letter}
          plainLanguageSummary={proposal.plain_language_summary}
          estimatedCost={proposal.estimated_cost ?? 0}
          durationDays={proposal.estimated_duration_days ?? 0}
        />

        <View style={styles.divider} />

        {/* SCI Score */}
        <PdfSciGauge sci={sci} />

        <View style={styles.divider} />

        {/* Compare Table */}
        <PdfCompareTable
          stepCount={steps.length}
          inspectionCount={proposal.total_inspections}
          gateCount={proposal.total_gates}
          hasCodeReferences={proposal.has_code_references}
          holdbackPercent={10}
          hasBcin={proProfile?.bcin_verified ?? false}
        />

        <View style={styles.divider} />

        {/* Journey Steps — may span multiple pages */}
        <PdfJourneyList steps={steps} />

        <View style={styles.divider} />

        {/* Payment Schedule */}
        <PdfPaymentTable
          milestones={milestones}
          estimatedCost={proposal.estimated_cost ?? 0}
        />

        <View style={styles.divider} />

        {/* Contractor Info */}
        <PdfContractorInfo
          contractorProfile={contractorProfile}
          proProfile={proProfile}
        />

        <View style={styles.divider} />

        {/* Terms + Disclaimer */}
        <PdfTerms />

        {/* Fixed footer with page numbers */}
        <View style={styles.footer} fixed>
          <Text>Generated by RenoNext</Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
